import { UserRole } from '../types/roles';
import { Permission } from '../types/auth';

/**
 * MATRIKS PERAN & HAK AKSES (RBAC) SALAM STAI AL-ITTIHAD
 */
export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  mahasiswa: [
    'materials:view',
    'video:watch',
    'quizzes:attempt',
    'assignments:submit',
    'discussions:view',
    'discussions:post',
    'progress:view_own',
    'academic:view_schedule',
    'academic:view_krs_khs',
  ],

  dosen: [
    'materials:view',
    'materials:manage',
    'materials:publish',
    'video:watch',
    'video:manage',
    'quizzes:attempt',
    'quizzes:manage',
    'assignments:manage',
    'assignments:grade',
    'discussions:view',
    'discussions:post',
    'discussions:moderate',
    'progress:view_own',
    'progress:view_class',
    'progress:export',
    'academic:view_schedule',
    'academic:input_final_grades',
    'academic:view_krs_khs',
  ],

  dosen_pa: [
    'materials:view',
    'materials:manage',
    'materials:publish',
    'video:watch',
    'video:manage',
    'quizzes:manage',
    'assignments:manage',
    'assignments:grade',
    'discussions:view',
    'discussions:post',
    'discussions:moderate',
    'progress:view_class',
    'academic:view_schedule',
    'academic:input_final_grades',
    'academic:view_krs_khs',
  ],

  kaprodi: [
    'materials:view',
    'materials:manage',
    'materials:publish',
    'video:watch',
    'video:manage',
    'quizzes:manage',
    'assignments:manage',
    'assignments:grade',
    'discussions:view',
    'discussions:moderate',
    'progress:view_class',
    'progress:export',
    'academic:view_schedule',
    'academic:view_periods',
    'academic:input_final_grades',
    'academic:view_krs_khs',
    'academic:manage_schedule',
  ],

  admin_akademik: [
    'materials:view',
    'quizzes:manage',
    'assignments:manage',
    'progress:view_class',
    'progress:export',
    'academic:view_schedule',
    'academic:view_periods',
    'academic:manage_periods',
    'academic:manage_schedule',
    'academic:input_final_grades',
    'academic:view_krs_khs',
    'sync:execute',
    'sync:view_logs',
    'users:manage',
    'audit:view',
  ],

  pimpinan: [
    'materials:view',
    'progress:view_class',
    'progress:export',
    'academic:view_schedule',
    'academic:view_periods',
    'academic:view_krs_khs',
    'sync:view_logs',
    'audit:view',
  ],

  administrator_sistem: [
    'materials:view',
    'materials:manage',
    'materials:publish',
    'video:watch',
    'video:manage',
    'quizzes:attempt',
    'quizzes:manage',
    'assignments:submit',
    'assignments:grade',
    'assignments:manage',
    'discussions:view',
    'discussions:post',
    'discussions:moderate',
    'progress:view_own',
    'progress:view_class',
    'progress:export',
    'academic:view_schedule',
    'academic:view_krs_khs',
    'academic:manage_schedule',
    'academic:view_periods',
    'academic:manage_periods',
    'academic:input_final_grades',
    'sync:execute',
    'sync:view_logs',
    'users:manage',
    'roles:manage',
    'audit:view',
    'system:configure',
  ],
};

export const ROLE_LABELS: Record<UserRole, string> = {
  mahasiswa: 'Mahasiswa',
  dosen: 'Dosen Pengampu',
  dosen_pa: 'Dosen Pembimbing Akademik',
  kaprodi: 'Ketua Program Studi',
  admin_akademik: 'Admin Akademik',
  pimpinan: 'Pimpinan STAI',
  administrator_sistem: 'Administrator Sistem',
};
